name: Joshua Zink-Duda
linkedin: joshua-zink-duda
homepage: https://joshua.zink-duda.com
education:
  school: Vanderbilt University
  degree: Bachelor of Science
  timeframe: 2016
  major: Computer Science, Mathematics
  minor: Astronomy

