languages_and_frameworks:
  title: Languages & Frameworks
  skills:
    skilled:
      - Ruby on Rails
      - Python
      - Java (Spring)
      - SQL
    familiar:
      - TypeScript (Next.js, React)

tools_and_platforms:
  title: Tools & Platforms
  skills:
    skilled:
      - REST APIs
      - Ansible
      - Rundeck
      - Git
    familiar:
      - AWS SQS
      - Terraform
      - CircleCI
      - Datadog

technical_areas:
  title: Technical Areas
  skills:
    - System Design
    - Authentication
    - Internationalization
    - API Design
    - Integrations
